### ISSUE TITLE
Mailgun timeout can prevent order submission.

### ISSUE THREAD

**Issue by msigley** [msigley/Shopp-Advanced-Validation#6]
A timeout from mailgun's servers can prevent order submission by disabling the email input on the checkout page, which prevents the field from being part of the browser's POST request to the server.

I am going to adjust the timeout to make it shorter, 30 seconds is way too long, and look at making use of the readonly attribute instead of disabling the input.

**Comment by dxdc** [comment]
Interesting -- what error message have you seen?

Also -- why disable the output or make it read-only? If the mailgun validation doesn't go through it shouldn't harm anything.

**Comment by msigley** [comment]
Fixed in a94c213348a3083404e0652bf47bafa37b584b6e
